version: "3.9"

services:
  web:
    build: .
    command: gunicorn auth_things_api.wsgi:application --bind 0.0.0.0:8001 --workers 4
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
